{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7e954431-cbd3-4ca7-9a69-7b49b6a66e99",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Modell geladen!\n",
      "\n",
      "🎥 Kamera läuft... Drücke 'q' zum Beenden oder 'c' für Korrektur.\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "81fef0edb8d4400ea4738fb00a0cccc6",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Image(value=b'', format='jpeg')"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🚪 Manuelle Beendigung durch Nutzer!\n",
      "🚪 Kamera gestoppt!\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Drücke Enter für Weiter, 'c' für Korrektur, 'q' zum Beenden:  \n"
     ]
    }
   ],
   "source": [
    "\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.applications import MobileNetV2\n",
    "from tensorflow.keras.preprocessing.image import img_to_array\n",
    "from tensorflow.keras.layers import Dense, GlobalAveragePooling2D\n",
    "from tensorflow.keras.models import Model\n",
    "import numpy as np\n",
    "import cv2\n",
    "import os\n",
    "import pandas as pd\n",
    "import time\n",
    "import matplotlib.pyplot as plt\n",
    "from IPython.display import display, clear_output\n",
    "from PIL import Image\n",
    "import ipywidgets as widgets\n",
    "\n",
    "# --- Konfigurationsvariablen ---\n",
    "MODEL_PATH = \"mobilenet_model.h5\"\n",
    "CSV_FILE = \"training_data/Classes_alle.csv\"\n",
    "IMG_SIZE = (224, 224)\n",
    "BATCH_SIZE = 32\n",
    "EPOCHS = 10\n",
    "LEARNING_RATE = 0.001\n",
    "\n",
    "# --- Labels aus CSV laden ---\n",
    "def load_labels_from_csv(csv_path):\n",
    "    if os.path.exists(csv_path):\n",
    "        df = pd.read_csv(csv_path)\n",
    "        return {int(row['label_id']): row['class_name'] for _, row in df.iterrows()}\n",
    "    return {}\n",
    "\n",
    "LABELS = load_labels_from_csv(CSV_FILE)\n",
    "num_classes = len(LABELS)\n",
    "\n",
    "# --- Modell laden oder neu erstellen ---\n",
    "def get_model(num_classes):\n",
    "    if num_classes == 0:\n",
    "        print(\"❌ Keine Klassen gefunden. Modell wird nicht geladen.\")\n",
    "        return None\n",
    "    \n",
    "    base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))\n",
    "    base_model.trainable = False\n",
    "    \n",
    "    x = GlobalAveragePooling2D()(base_model.output)\n",
    "    x = Dense(128, activation='relu')(x)\n",
    "    output = Dense(num_classes, activation='softmax')(x)\n",
    "    \n",
    "    model = Model(inputs=base_model.input, outputs=output)\n",
    "    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE),\n",
    "                  loss='sparse_categorical_crossentropy',\n",
    "                  metrics=['accuracy'])\n",
    "    return model\n",
    "\n",
    "model = get_model(num_classes)\n",
    "\n",
    "if model and os.path.exists(MODEL_PATH):\n",
    "    model.load_weights(MODEL_PATH)\n",
    "    print(\"✅ Modell geladen!\")\n",
    "else:\n",
    "    print(\"❌ Kein trainiertes Modell gefunden!\")\n",
    "\n",
    "# --- Bildvorverarbeitung für Klassifikation ---\n",
    "def preprocess_frame(frame):\n",
    "    if frame is None or frame.size == 0:\n",
    "        print(\"❌ Fehler: Ungültiges Bild erhalten!\")\n",
    "        return None\n",
    "    \n",
    "    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n",
    "    frame_resized = cv2.resize(frame_rgb, IMG_SIZE)\n",
    "    frame_array = img_to_array(frame_resized) / 255.0\n",
    "    return np.expand_dims(frame_array, axis=0)\n",
    "\n",
    "# --- Klassifikation durchführen ---\n",
    "def classify_image(model, frame):\n",
    "    img_tensor = preprocess_frame(frame)\n",
    "    if img_tensor is None:\n",
    "        return [(\"Fehler\", 0.0)]\n",
    "    \n",
    "    predictions = model.predict(img_tensor, verbose=0)[0]\n",
    "    top_2 = np.argsort(predictions)[-2:][::-1]\n",
    "    return [(LABELS.get(i, \"Unbekannt\"), predictions[i]) for i in top_2]\n",
    "\n",
    "# --- Kontinuierlicher Kamera-Stream mit Korrektur ---\n",
    "def live_classification():\n",
    "    cap = cv2.VideoCapture(0)\n",
    "    if not cap.isOpened():\n",
    "        print(\"❌ Fehler: Kamera nicht verfügbar!\")\n",
    "        return\n",
    "\n",
    "    print(\"\\n🎥 Kamera läuft... Drücke 'q' zum Beenden oder 'c' für Korrektur.\")\n",
    "    image_widget = widgets.Image(format='jpeg')\n",
    "    display(image_widget)\n",
    "\n",
    "    try:\n",
    "        while True:\n",
    "            ret, frame = cap.read()\n",
    "            if not ret or frame is None or frame.size == 0:\n",
    "                print(\"❌ Fehler beim Lesen des Kamerabilds! Neuer Versuch...\")\n",
    "                time.sleep(0.5)\n",
    "                continue\n",
    "\n",
    "            predictions = classify_image(model, frame)\n",
    "            text_lines = [f\"{label}: {prob:.2%}\" for label, prob in predictions]\n",
    "            y_offset = 50\n",
    "            for line in text_lines:\n",
    "                cv2.putText(frame, line, (10, y_offset), cv2.FONT_HERSHEY_SIMPLEX, 2.1, (0, 255, 0), 5)\n",
    "                y_offset += 80\n",
    "\n",
    "            _, buffer = cv2.imencode('.jpg', frame)\n",
    "            image_widget.value = buffer.tobytes()\n",
    "            \n",
    "            key = input(\"Drücke Enter für Weiter, 'c' für Korrektur, 'q' zum Beenden: \").strip()\n",
    "            if key == 'q':\n",
    "                break\n",
    "            elif key == 'c':\n",
    "                correct_classification(frame)\n",
    "    except KeyboardInterrupt:\n",
    "        print(\"🚪 Manuelle Beendigung durch Nutzer!\")\n",
    "    \n",
    "    cap.release()\n",
    "    print(\"🚪 Kamera gestoppt!\")\n",
    "\n",
    "# --- Korrektur & neue Klassen hinzufügen ---\n",
    "def correct_classification(frame):\n",
    "    if frame is None or frame.size == 0:\n",
    "        print(\"❌ Fehler: Ungültiges Bild zur Korrektur!\")\n",
    "        return\n",
    "\n",
    "    print(\"\\n📌 Verfügbare Klassen:\")\n",
    "    for idx, class_name in LABELS.items():\n",
    "        print(f\"{idx}: {class_name}\")\n",
    "\n",
    "    new_class = input(\"Neue Klasse oder vorhandene Nummer eingeben: \").strip()\n",
    "\n",
    "    if new_class.isdigit() and int(new_class) in LABELS:\n",
    "        class_name = LABELS[int(new_class)]\n",
    "    else:\n",
    "        class_name = new_class\n",
    "        new_label_id = max(LABELS.keys(), default=-1) + 1\n",
    "        LABELS[new_label_id] = class_name\n",
    "\n",
    "        with open(CSV_FILE, \"a\") as f:\n",
    "            f.write(f\"{new_label_id},{class_name}\\n\")\n",
    "        print(f\"✅ Neue Klasse '{class_name}' hinzugefügt!\")\n",
    "\n",
    "    class_dir = os.path.join(TRAINING_DATA_DIR, class_name)\n",
    "    os.makedirs(class_dir, exist_ok=True)\n",
    "    \n",
    "    img_name = os.path.join(class_dir, f\"{int(time.time())}.jpg\")\n",
    "    cv2.imwrite(img_name, frame)\n",
    "    print(f\"📷 Bild gespeichert: {img_name}\")\n",
    "\n",
    "# --- Skript starten ---\n",
    "if __name__ == \"__main__\":\n",
    "    live_classification()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dfe9afea-2fa1-49a9-836b-a2217d5699f1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10 (Jupyter)",
   "language": "python",
   "name": "jupyter-py310"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
